### ISSUE TITLE
map_ellipses

### ISSUE THREAD

**Issue by Luantimes2** [michael-petersen/elliptical#1]
Hi Mike
In the function map_ellipses, the parameter numZ does not work, I guess it should be in the line 95. And the condition in line 116 should also include (phi < 0.3).
I will also suggest to set a parameter for the tolerance of "e" in line 116, saying (b/a)<etol instead of b/a<0.5 in case that the bar become bulking.
Thanks
Luan

**Comment by michael-petersen** [comment]
-Good catch on numZ, I had hardwired that in accidentally.
-I added support for phi tolerance to both the ellipse map and the optimal ellipse; phi should really only be used if the image is pre-aligned to be along the y-axis, otherwise phi will need to be a free parameter to fit the ellipses properly.
-I added ETOL, good suggestion. ETOL=0.5 is still fairly conservative, I think, but we could definitely see some very round bars.
